Feature: Add converte Array of Object
craftgear/snake-camel pull request #19
Opened 2021-02-25 07:33 UTC by xPolo360

Hello,

Thank you for your library.
I allow myself a small contribution because I noticed that your library does not take into account the case for the original was given an array of javacript object.

example:
```javascript
toCamel(
  [ // <== ARRAY
    { fooBar: 'fooBar', barBaz: 1 },
    { fooBar: 'foo', quxBar: 'bar' }
  ]
);
// yields
// { <== OBJECT
//    { fooBar: 'fooBar', barBaz: 1 },
//    { fooBar: 'foo', quxBar: 'bar' }
// }
```

I allows some optimization of typing and code.

Regards.

2021-02-25 10:57 UTC, craftgear commented
Hi,

Thanks for your contribution!

As you pointed out, the implementation for an `Array` of `Object`s are omitted.
And it's intentional.

Because you can just map `toCamel` or `toSnake` over an `Array` and the job gets done.
Like so:

```
  const camelCased = [
    { fooBar: 'fooBar', barBaz: 1 },
    { fooBar: 'foo', quxBar: 'bar' }
  ];

  var snaked = camelCased.map(toSnake);
```

I prefer handling this with innate JavaScript functions to covering it in my small library.

I'll include this use case in specs and `README.md`.

Thanks again.

2021-02-25 13:33 UTC, xPolo360 commented
Sure it's a way to do which I had not thought.

The idea was for me to put in my helper fetch the'toCamel to convert dice the arrival of my API.

And in this case my api sometimes returns objects and sometimes arrays depending on whether I want to retrieve a resource or a collection.
And in this case I do not have to ask myself the question of knowing if it is an object or an array your library takes care of it.

But I understand your point of view.

Afterwards you can keep the typings that I suggest to you because it allows to keep the type of the return according to the typings of input.

For autocompletion it's much more practical;)

2021-02-26 12:29 UTC, craftgear commented
Sweet! Let me take a look at  it.

2021-02-27 11:57 UTC, craftgear requested changes

2021-02-27 11:57 UTC, craftgear commented on src/index.spec.ts
> +});
I think you can safely delete these specs.

2021-02-27 11:57 UTC, craftgear commented on src/index.ts
> +  return recursive({ key: data }).key;
Where does this `key` come from?

2021-09-06 00:31 UTC, craftgear commented
It's stale, closing this.

2021-09-06 00:31 UTC, closed without merging